# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('idn', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainHandles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField()),
                ('created', models.DateField(auto_now_add=True)),
                ('contact_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.ContactHandle')),
            ],
        ),
        migrations.CreateModel(
            name='DomainProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DomainRegistrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('email2', models.CharField(blank=True, max_length=200)),
                ('email3', models.CharField(blank=True, max_length=200)),
                ('house_number', models.CharField(max_length=10)),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(blank=True, max_length=200)),
                ('street3', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('suburb', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.Identity')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('registration_period', models.IntegerField()),
                ('anniversary', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrantHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.PersonalDetail')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.DomainProvider')),
            ],
        ),
        migrations.CreateModel(
            name='TopLevelDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100, unique=True)),
                ('idn_zone', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopLevelDomainProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_notification_period_days', models.IntegerField()),
                ('renewal_period', models.IntegerField(default=30)),
                ('grace_period_days', models.IntegerField(default=30)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.DomainProvider')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.TopLevelDomain')),
            ],
        ),
        migrations.AddField(
            model_name='registereddomain',
            name='tld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.TopLevelDomain'),
        ),
        migrations.AddField(
            model_name='registereddomain',
            name='tld_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.TopLevelDomainProvider'),
        ),
        migrations.AddField(
            model_name='domainregistrant',
            name='registered_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.RegisteredDomain'),
        ),
        migrations.AddField(
            model_name='domainregistrant',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.RegistrantHandle'),
        ),
        migrations.AddField(
            model_name='domainhandles',
            name='registered_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.RegisteredDomain'),
        ),
        migrations.AddField(
            model_name='contacthandle',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.ContactType'),
        ),
        migrations.AddField(
            model_name='contacthandle',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.PersonalDetail'),
        ),
        migrations.AddField(
            model_name='contacthandle',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.DomainProvider'),
        ),
        migrations.AlterUniqueTogether(
            name='registereddomain',
            unique_together=set([('domain', 'tld', 'active')]),
        ),
        migrations.AlterUniqueTogether(
            name='domainregistrant',
            unique_together=set([('registered_domain', 'registrant', 'active')]),
        ),
        migrations.AlterUniqueTogether(
            name='domainhandles',
            unique_together=set([('registered_domain', 'contact_handle', 'active')]),
        ),
    ]
