# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0002_auto_20161214_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopLevelDomainProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_notification_period_days', models.IntegerField()),
                ('grace_period_days', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='domainprovider',
            name='zones',
        ),
        migrations.AddField(
            model_name='topleveldomainprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.DomainProvider'),
        ),
        migrations.AddField(
            model_name='topleveldomainprovider',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.TopLevelDomain'),
        ),
    ]
