# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0003_auto_20161216_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='topleveldomainprovider',
            name='renewal_period',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
