# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0003_auto_20161224_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='identity',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='first_name',
            field=models.CharField(default='Change', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='surname',
            field=models.CharField(default='Me', max_length=200),
            preserve_default=False,
        ),
    ]
