# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0004_auto_20161226_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
    ]
