# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0004_topleveldomainprovider_renewal_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='emai2',
            new_name='email2',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='emai3',
            new_name='email3',
        ),
    ]
