# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0005_auto_20161226_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='fax',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='telephone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
