# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0005_auto_20161216_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField(unique=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('registration_period', models.IntegerField()),
                ('anniversary', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='domain',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='created',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='registration_period',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='updated',
        ),
        migrations.AlterField(
            model_name='domain',
            name='idn',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='domainprovider',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topleveldomain',
            name='idn_zone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topleveldomain',
            name='zone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='registereddomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.Domain'),
        ),
        migrations.AddField(
            model_name='registereddomain',
            name='tld_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.TopLevelDomainProvider'),
        ),
    ]
