# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0006_auto_20170101_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacthandle',
            name='contact_type',
        ),
        migrations.AddField(
            model_name='domainhandles',
            name='contact_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domain_api.ContactType'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='domainhandles',
            unique_together=set([('registered_domain', 'contact_type', 'contact_handle', 'active')]),
        ),
    ]
