# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0007_auto_20161217_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DomainHandles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField()),
                ('created', models.DateField(auto_now_add=True)),
                ('contact_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.ContactHandle')),
            ],
        ),
        migrations.CreateModel(
            name='DomainRegistrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrantHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PersonalDetails',
            new_name='PersonalDetail',
        ),
        migrations.AddField(
            model_name='registereddomain',
            name='tld',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='domain_api.TopLevelDomain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identity',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registereddomain',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='topleveldomainprovider',
            name='grace_period_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='topleveldomainprovider',
            name='renewal_period',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterUniqueTogether(
            name='registereddomain',
            unique_together=set([('domain', 'tld', 'active')]),
        ),
        migrations.AddField(
            model_name='registranthandle',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.PersonalDetail'),
        ),
        migrations.AddField(
            model_name='registranthandle',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.DomainProvider'),
        ),
        migrations.AddField(
            model_name='domainregistrant',
            name='registered_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.RegisteredDomain'),
        ),
        migrations.AddField(
            model_name='domainregistrant',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.RegistrantHandle'),
        ),
        migrations.AddField(
            model_name='domainhandles',
            name='registered_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.RegisteredDomain'),
        ),
        migrations.AddField(
            model_name='contacthandle',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.ContactType'),
        ),
        migrations.AddField(
            model_name='contacthandle',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.PersonalDetail'),
        ),
        migrations.AddField(
            model_name='contacthandle',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_api.DomainProvider'),
        ),
        migrations.AlterUniqueTogether(
            name='domainregistrant',
            unique_together=set([('registered_domain', 'registrant', 'active')]),
        ),
        migrations.AlterUniqueTogether(
            name='domainhandles',
            unique_together=set([('registered_domain', 'contact_handle', 'active')]),
        ),
    ]
