# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0007_auto_20170102_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainprovider',
            name='slug',
            field=models.CharField(default='068d6fc2-24bb-4ca3-ac28-28cbeb71a9f9', max_length=100),
        ),
    ]
