# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0008_domainprovider_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainprovider',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
