# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0010_auto_20170104_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacthandle',
            name='handle',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='domainhandles',
            name='registered_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_handles', to='domain_api.RegisteredDomain'),
        ),
        migrations.AlterField(
            model_name='domainregistrant',
            name='registered_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrant', to='domain_api.RegisteredDomain'),
        ),
        migrations.AlterField(
            model_name='registranthandle',
            name='handle',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
