# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='authcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='disclose_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='disclose_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='disclose_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='disclose_fax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='disclose_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='disclose_telephone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='postal_info_type',
            field=models.CharField(choices=[('int', 'international'), ('loc', 'local')], default='loc', max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='street1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='street2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='street3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='suburb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='authcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='country',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='disclose_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrant',
            name='disclose_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrant',
            name='disclose_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrant',
            name='disclose_fax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrant',
            name='disclose_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrant',
            name='disclose_telephone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrant',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='postal_info_type',
            field=models.CharField(choices=[('int', 'international'), ('loc', 'local')], default='loc', max_length=3),
        ),
        migrations.AddField(
            model_name='registrant',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='street1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='street2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='street3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='suburb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
