# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topleveldomainprovider',
            name='anniversary_notification_period_days',
            field=models.IntegerField(default=30),
        ),
    ]
