# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0002_auto_20170326_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='address',
            new_name='ip',
        ),
    ]
