# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0002_auto_20170218_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
