# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0003_auto_20170327_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameserverhost',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
