# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0003_auto_20170218_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='idn',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
