# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain_api', '0004_remove_defaultaccountcontact_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultaccountcontact',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultcontact',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='defaultaccountcontact',
            unique_together=set([('project_id', 'contact_type', 'account_template', 'provider')]),
        ),
    ]
