# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0004_nameserverhost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameserverhost',
            name='roid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
