# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0004_auto_20170224_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
