# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain_api', '0005_auto_20170224_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('address_type', models.CharField(choices=[('v4', 'ipv4'), ('v6', 'ipv6')], default='v4', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameserverHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('domain_nameserver', models.ManyToManyField(to='domain_api.RegisteredDomain')),
            ],
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='nameserver_host',
            field=models.ManyToManyField(to='domain_api.NameserverHost'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
