# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0006_auto_20170329_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereddomain',
            old_name='anniversary',
            new_name='expiration',
        ),
        migrations.RenameField(
            model_name='topleveldomainprovider',
            old_name='anniversary_notification_period_days',
            new_name='expiration_notification_period_days',
        ),
    ]
