# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0006_auto_20170306_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddomain',
            name='authcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registereddomain',
            name='roid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
