# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0007_auto_20170330_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='topleveldomain',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
