# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0008_topleveldomain_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topleveldomain',
            name='slug',
        ),
    ]
