# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0008_registereddomain_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nameserverhost',
            old_name='domain_nameserver',
            new_name='domain_nameservers',
        ),
    ]
