# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0009_auto_20170310_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='account_template',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='domain_api.AccountDetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nameserverhost',
            name='domain_nameservers',
            field=models.ManyToManyField(related_name='ns', to='domain_api.RegisteredDomain'),
        ),
    ]
