# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0010_auto_20170311_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='account_template',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='domain_api.AccountDetail'),
            preserve_default=False,
        ),
    ]
