# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0010_topleveldomain_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topleveldomain',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
