# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain_api', '0011_registrant_account_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaultaccountcontact',
            unique_together=set([('project_id', 'contact_type', 'account_template', 'provider', 'mandatory')]),
        ),
    ]
