# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0011_auto_20170404_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='default_registrant',
            field=models.NullBooleanField(unique=True),
        ),
    ]
