# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0012_accountdetail_default_registrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='house_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
