# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0012_auto_20170323_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='idn',
        ),
        migrations.RemoveField(
            model_name='topleveldomain',
            name='idn_zone',
        ),
    ]
