# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0013_auto_20170406_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='email3',
        ),
    ]
