# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0014_auto_20170406_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainprovider',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topleveldomainprovider',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
