# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 08:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain_api', '0015_auto_20170406_0841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountdetail',
            unique_together=set([('project_id', 'default_registrant')]),
        ),
    ]
