# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0016_auto_20170407_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='default_registrant',
            field=models.NullBooleanField(),
        ),
    ]
