# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 19:05
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0017_auto_20170518_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddomain',
            name='domain_status',
            field=django_mysql.models.JSONField(default=None),
        ),
    ]
