# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 19:13
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0018_registereddomain_domain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereddomain',
            name='domain_status',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
    ]
