# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 03:32
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0019_auto_20170603_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_status',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='contact_status',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
    ]
