# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 03:35
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0020_auto_20170604_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameserverhost',
            name='nameserver_status',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
    ]
