# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 06:31
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0021_nameserverhost_nameserver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='disclose',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='non_disclose',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='disclose',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='non_disclose',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='disclose',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='non_disclose',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
    ]
