# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 07:44
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0022_auto_20170604_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='street',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='street',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
    ]
