# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0023_auto_20170604_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='non_disclose',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='non_disclose',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='non_disclose',
        ),
    ]
