# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0025_registereddomain_nameservers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='house_number',
        ),
    ]
