# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0026_auto_20170612_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='disclose_address',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='disclose_company',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='disclose_email',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='disclose_fax',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='disclose_name',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='disclose_telephone',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='street3',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disclose_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disclose_company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disclose_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disclose_fax',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disclose_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='disclose_telephone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='street3',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='disclose_address',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='disclose_company',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='disclose_email',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='disclose_fax',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='disclose_name',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='disclose_telephone',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='street3',
        ),
    ]
