# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0027_auto_20170612_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='middle_name',
        ),
    ]
