# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0028_remove_accountdetail_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetail',
            name='suburb',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='suburb',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='suburb',
        ),
    ]
