# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 09:24
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0029_auto_20170612_0859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='nameserver_host',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='nameserver',
            name='domain_nameservers',
        ),
        migrations.AddField(
            model_name='nameserver',
            name='ip',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='IpAddress',
        ),
    ]
