# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain_api', '0030_auto_20170614_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameserver',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameserver',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='nameserver_status',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nameservers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameserver',
            name='roid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nameserver',
            name='tld_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domain_api.TopLevelDomainProvider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nameserver',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
