# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0031_auto_20170614_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nameserverhost',
            name='nameserver',
        ),
        migrations.RemoveField(
            model_name='nameserverhost',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='nameserverhost',
            name='tld_provider',
        ),
        migrations.DeleteModel(
            name='NameserverHost',
        ),
    ]
