# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 10:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain_api', '0032_auto_20170614_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='project_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='project_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='defaultaccountcontact',
            old_name='project_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='defaultaccounttemplate',
            old_name='project_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='defaultcontact',
            old_name='project_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='defaultregistrant',
            old_name='project_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='nameserver',
            old_name='project',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='registrant',
            old_name='project_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='accountdetail',
            unique_together=set([('user', 'default_registrant')]),
        ),
        migrations.AlterUniqueTogether(
            name='defaultaccountcontact',
            unique_together=set([('user', 'contact_type', 'account_template', 'provider', 'mandatory')]),
        ),
        migrations.AlterUniqueTogether(
            name='defaultaccounttemplate',
            unique_together=set([('user', 'provider', 'account_template')]),
        ),
        migrations.AlterUniqueTogether(
            name='defaultcontact',
            unique_together=set([('user', 'contact_type', 'contact', 'provider')]),
        ),
        migrations.AlterUniqueTogether(
            name='defaultregistrant',
            unique_together=set([('user', 'registrant')]),
        ),
    ]
