# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0035_registereddomain_domain_registrant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereddomain',
            old_name='status',
            new_name='status_domain',
        ),
    ]
