# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0036_auto_20170616_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereddomain',
            old_name='domain_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='registereddomain',
            name='status_domain',
        ),
    ]
