# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0038_auto_20170616_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereddomain',
            old_name='domain_registrant',
            new_name='registrant',
        ),
    ]
