# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0039_auto_20170616_0951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domainregistrant',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='domainregistrant',
            name='registered_domain',
        ),
        migrations.RemoveField(
            model_name='domainregistrant',
            name='registrant',
        ),
        migrations.DeleteModel(
            name='DomainRegistrant',
        ),
    ]
