# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0044_delete_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nameserver',
            old_name='ip',
            new_name='addr',
        ),
        migrations.RenameField(
            model_name='nameserver',
            old_name='status',
            new_name='status_nameserver',
        ),
    ]
