# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0046_auto_20170616_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='status',
            new_name='status_contact',
        ),
        migrations.RenameField(
            model_name='registrant',
            old_name='status',
            new_name='status_contact',
        ),
    ]
