# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0047_auto_20170616_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='registrant',
            old_name='contact_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status_contact',
        ),
        migrations.RemoveField(
            model_name='registrant',
            name='status_contact',
        ),
    ]
