# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0048_auto_20170616_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='disclose',
            new_name='non_disclose',
        ),
    ]
