# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0049_auto_20170617_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='disclose',
            new_name='non_disclose',
        ),
        migrations.RenameField(
            model_name='registrant',
            old_name='disclose',
            new_name='non_disclose',
        ),
    ]
