# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_api', '0051_auto_20170625_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereddomain',
            name='fqdn',
            field=models.CharField(default='changeme', max_length=200),
            preserve_default=False,
        ),
    ]
